### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by WxWatch**
Very basic styling updates to the overall layout, menu, and filament table actions.

### CODE REVIEW

**Comment by sargonas** [comment]
Looks great! However, it looks like while the overall layout was cleaned up and the filaments index was given some sexy, the prints index still looks like the old format? If that's intended, i can go ahead and accept this in and carry over the changes by hand from filaments to them.. I'm assuming it won't be that hard.

**Comment by WxWatch** [comment]
Yes, since I made a few changes to the HTML structure of the application, I'm trying to get a pull request in earlier than not. This way, if anyone else is wanting to assist with styling updates, they won't run into issues with the overall structure of the application.

But yes, the changes should be straightforward enough that you can apply them to some of the other pages, but I'm still also planning on putting in more time making everything look slicker.

**Comment by sargonas** [comment]
Awesome, sounds good! I'll get them merged in later this morning then! (I'll probably create a new "UI overhaul" branch, till it's primetime ready.)

**Comment by sargonas** [comment]
Ok I've merged this into the ui_design branch while I continue to build more off of it. Feel free to work off of that branch moving ofward as well to make the collaboration easier to merge in and track!

**Pull request closed without merging**
